---
resources:
- name: newman-repo
  type: git
  source:
    uri: https://github.com/gauravopcito/ConcourseCI-Newman.git
    branch: master
  
jobs:
- name: test-rest-api
  public: true
  plan:
  - get: newman-repo
    trigger: true
  - task: test-api
    file: newman-repo/newman/newman-task.yml
    params: { "ENVIRONMENT_URL": "newman/test-environment.json", "GLOBAL_URL": "newman/test-globals.json", "COLLECTION_URL": "newman/test-collection.json" }