---
resources:
- name: newman-repo
  type: git
  source: https://github.com/gauravopcito/ConcourseCI-Newman.git
    uri:
  
jobs:
- name: test-rest-api
  public: true
  plan:
  - get: newman-repo
  - task: test-api
    file: newman-repo/newman/newman-task.yml
    params: { "ENVIRONMENT_URL": "https://github.com/gauravopcito/ConcourseCI-Newman/blob/master/newman/test-environment.json", "COLLECTION_URL": "https://github.com/gauravopcito/ConcourseCI-Newman/blob/master/newman/test-collection.json" }